name: Ppipeline v2

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: helm-gh-runner

    steps:
    - uses: actions/checkout@v3
        
    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        ./mvnw -B verify
        echo "Carpeta Jar"
        ls -la 
        ls target

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v4
      with:
        name: jar
        path: target/ 
        retention-days: 1
    
  reusable:
    needs: build
    uses: CMelerom/Github-action/.github/workflows/reusable.yml@master
    with:
      image: "app"          
      deployment: "petclinic-deployment"
    secrets:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
